### ISSUE TITLE
[BUG] get-meals-today 엔드포인트 404 오류 반환

### ISSUE THREAD

**Issue by key-del-jeeinho** [Team-Dotori/golabab-lunch-server#9]
**버그 요약**
`host:3000/api/v1/meals/get-meals-today` 로 요청을 보내자, 404 오류가 발생합니다
Github mainbranch 의 code 를 다운받아 서버를 실행하였습니다

**스크린샷**
![](https://cdn.discordapp.com/attachments/736846956504285194/904966918501453854/unknown.png)
![](https://cdn.discordapp.com/attachments/736846956504285194/904967009647886417/unknown.png)

**환경 스펙**
| | |
|:--------------:|-------------------------------|
|   server-os  | raspbian                                 |
|       host      | 10.120.73.152                        |
|       port      | 3000                                       |
| request by  | postman                                |

**오류 로그**
- request
```http
GET | 10.120.73.152:3000/api/v1/meals/get-meals-today
```
- response
```json
{
    "statusCode": 404,
    "message": "Cannot GET /api/v1/meals/get-meals-today",
    "error": "Not Found"
}
```

**Comment by songyouhyun** [comment]
![스크린샷 2021-11-02 오후 2 44 32](https://user-images.githubusercontent.com/68471917/139793248-629b1826-bb50-48fc-afcd-6fe5317d3a2d.png)
README에 있는 API 명세를 확인해주시기 바라겠습니다!

**Comment by songyouhyun** [comment]
![스크린샷 2021-11-02 오후 2 51 23](https://user-images.githubusercontent.com/68471917/139793368-a06e21f7-0e39-425d-89bf-4e79564640b3.png)
게다가 @key-del-jeeinho 님이 보내주신 Log 스크린샷에도 이와 동일하게 적혀져있습니다.

**Comment by key-del-jeeinho** [comment]
![image](https://user-images.githubusercontent.com/77221262/139794832-8ceb2873-2caa-438e-b98d-d6ccacc9adf1.png)
아 세부명세랑 다르네요 확인하였습니다
